safe: true
markdown: kramdown
highlighter: pygments
permalink: /:title.html

default_theme: ribbon
default_width: 792
default_lang: en
default_body_class: list

author:
    name: Joanna Lamch
    url:  http://jlamch.net/iotexercises
    company:
        name: JL System 
        # url:  http://example.com/

fork_url: http://jlamch.net/iotexercises
progress: true
line_numbers: true
