safe: true
markdown: kramdown
highlighter: pygments
permalink: /:title.html

default_theme: bright
default_width: 792
default_lang: en
default_body_class: list

author:
    name: Joanna Lamch
    url:  http://jlamch.net
    company:
        name: 
        # url:  http://example.com/

fork_url: 
progress: true
line_numbers: true
